FROM python:3.10-slim

WORKDIR /app

# Ambil requirements.txt dari folder paling luar (repo root)
COPY requirements.txt /app/requirements.txt
RUN pip install --no-cache-dir -r /app/requirements.txt

# Salin semua isi file ke folder /app
COPY . /app

EXPOSE 8000

CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]
