FROM python:3.10-slim

WORKDIR /app

# Mengambil file requirements.txt dan seluruh isi folder dari root repositori
COPY requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt

COPY . ./

EXPOSE 8000

CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]
